#DB 설정
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/pingpong
    username: sa
    password: 1234

  #JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create

    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true